version: '2'
services:
  nginx-proxy:
    build: nginx/
    ports:
      - "80:80"
    network_mode: "host"

  db:
    network_mode: "host"
    image: bitnami/postgresql:latest
    environment:
      - POSTGRESQL_PASSWORD=12345
      - POSTGRESQL_DATABASE=KS
    volumes:
      - /var/postgres_bitnami:/bitnami/postgresql
  web:
    build: dotnet/.
    network_mode: "host"
    restart: on-failure
  web2:
    build: dotnet-staging/.
    network_mode: "host"
    restart: on-failure

