version: '2'
services:
  nginx-proxy:
    build: nginx/
    ports:
      - "80:80"
    network_mode: "host"
  web:
    build: dotnet/.
    container_name: node
    network_mode: "host"
  db:
    network_mode: "host"
    image: bitnami/postgresql:latest
    environment:
      - POSTGRESQL_PASSWORD=password123
      - POSTGRESQL_USERNAME=user
      - POSTGRESQL_DATABASE=database
