version: '2'
services:
  nginx-proxy:
    build: nginx/
    ports:
      - "80:80"
    network_mode: "host"

  db:
    network_mode: "host"
    image: bitnami/postgresql:latest
    environment:
      - POSTGRESQL_PASSWORD=12345
      - POSTGRESQL_DATABASE=KS
    volumes:
      - /var/postgres_bitnami:/bitnami/postgresql
  web:
    build: dotnet/.
    network_mode: "host"
    restart: on-failure
    volumes:
      - /var/upload:/var/upload
  web-staging:
    build: dotnet-staging/.
    network_mode: "host"
    restart: on-failure
    volumes:
      - /var/upload:/var/upload
  registry:
    image: registry:2
    restart: always
    volumes:
      - /var/data:/var/lib/registry 
    ports:
      - "8888:5000"
  sen:
   image: tomastomecek/sen
   environment:
     - TERM
   privileged: true
   volumes:
    - /var/run/docker.sock:/run/docker.sock

