version: '2'
services:
  nginx-proxy:
    build: nginx/
    ports:
      - "80:80"
    network_mode: "host"
  db:
     image: mysql
     command: mysqld --sql_mode="" --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;'
     network_mode: "host"
     container_name: "mysql"
     environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
  web:
    build: dotnet/.
    network_mode: "host"
    restart: on-failure
    volumes:
      - /var/upload:/var/upload/screenshots
  web-staging:
    build: dotnet-staging/.
    network_mode: "host"
    restart: on-failure
    volumes:
      - /var/upload:/var/upload/sceenshots
  web-test:
    build: dotnet_test/.
    network_mode: "host"
  registry:
    image: registry:2
    restart: always
    volumes:
      - /var/data:/var/lib/registry 
    ports:
      - "8888:5000"
